version: "3.2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka
    ports:
      - "9094:9094"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
  
  mastodon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mastodon-to-kafka
    ports:
      - "8080:80"
    depends_on: 
      - kafka
    environment:
      KAFKA_TLS_ENABLED: "false"
      KAFKA_SASL_MECHANISM: "none"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: "mastodon_topic"
      KAFKA_CONSUMER_GROUP: "mastodon"
      PRINT_KAFKA_MESSAGE: "false"